### ISSUE TITLE
Warning: You are manually calling a React.PropTypes validation function ...

### ISSUE THREAD

**Issue by simeg** [arqex/react-datetime-playground#3]
The console is going crazy with a lot of warnings over the same thing but for different props.

`Warning: You are manually calling a React.PropTypes validation function for ...`

I've been doing some Googling but I can't seem to find anything. It's weird because the component is working in production when you are using it as you should, so there's probably some error in the server configuration.

**Comment by arqex** [comment]
Hey @simeg 

Sorry I am a bit out of the project lately, it's a very busy month September in ycbm, so it's hard to me to find time to pay attention to the datepicker.

But I see you can manage well yourself, you already have added a git submodules file here. Git submodules are always tricky.

As for this particular issue, I am not sure, but it sounds to me that is related to the way that the module is used.

When the project is using classes and extending React.Component, there are some methods that can be called but not others, see `getInitialState`. When the project is creating the components using `React.createClass` it's the opposite.

Without having a look at the code, Maybe React is getting being used in both ways by the project, and we would need to access to React.PropTypes in a different way?

Hope it helps somehow ;)

**Comment by simeg** [comment]
This issue was fixed in [this commit](https://github.com/arqex/react-datetime-playground/commit/b8f28f5558284d73eaf2ddaa348b758bff7692d0).

**Comment by arqex** [comment]
Oooh so it was a problem of versions, interesting...
